// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQYS8HmiEN-lgVsx3_btWPNgO9jpSqRCg',
    appId: '1:47252981347:web:78916ce9f5af03b18e5a56',
    messagingSenderId: '47252981347',
    projectId: 'mapdb-f6986',
    authDomain: 'mapdb-f6986.firebaseapp.com',
    databaseURL: 'https://mapdb-f6986-default-rtdb.firebaseio.com',
    storageBucket: 'mapdb-f6986.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL5K78bBnP0xtoABiApy50C2SIQLQ3Z0c',
    appId: '1:47252981347:android:12da6e18957970b98e5a56',
    messagingSenderId: '47252981347',
    projectId: 'mapdb-f6986',
    databaseURL: 'https://mapdb-f6986-default-rtdb.firebaseio.com',
    storageBucket: 'mapdb-f6986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBX1-tactGteaRYrjZt4ayGGLla-9Sso',
    appId: '1:47252981347:ios:eb65e4f33a1657ea8e5a56',
    messagingSenderId: '47252981347',
    projectId: 'mapdb-f6986',
    databaseURL: 'https://mapdb-f6986-default-rtdb.firebaseio.com',
    storageBucket: 'mapdb-f6986.appspot.com',
    iosBundleId: 'com.example.restaurantReservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJBX1-tactGteaRYrjZt4ayGGLla-9Sso',
    appId: '1:47252981347:ios:0161fd61e192ebd48e5a56',
    messagingSenderId: '47252981347',
    projectId: 'mapdb-f6986',
    databaseURL: 'https://mapdb-f6986-default-rtdb.firebaseio.com',
    storageBucket: 'mapdb-f6986.appspot.com',
    iosBundleId: 'com.example.restaurantReservation.RunnerTests',
  );
}
